CapaAsilo/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;
using ClosedXML.Excel;

namespace CapaAsilo.Controllers
{
    public class MedicoController : Controller
    {

        // GET: Medico
        //******************* VISTAS ********************
        #region VISTAS
        public ActionResult SolicitudCitas ()
        {
            return View();
        }
         
        public ActionResult Pacientes()
        {
            return View();
        }

        public ActionResult FichaMedica()
        {
            return View();
        }
        public ActionResult Menu()
        {
            return View();
        }

        #endregion


        //***************** FICHA MEDICA ********************
        #region FICHA MEDICA
        public JsonResult VerFichaMedica(int IdCita)
        {
            Ficha objeto = new CN_Ficha().VerFicha(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }
        public JsonResult VerFichaMedica2(int IdCita)
        {
            VerExamen objeto = new CN_Ficha().VerFicha2(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }
        public JsonResult VerFichaMedica3(int IdCita)
        {
            VerMedicamento objeto = new CN_Ficha().VerFicha3(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //***************** CITAS MEDICAS ********************
        #region CITAS MEDICAS
        [HttpGet]
        public ActionResult ListarCitas()
        {

            List<CitaMedica> olista = new List<CitaMedica>();

            olista = new CN_CitasMedicas().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarCitaMedica(CitaMedica objeto) // guardar ficha medica
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdCita == 0)
            {
                resultado = new CN_CitasMedicas().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_CitasMedicas().Editar(objeto, out mensaje);
             

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult EliminarCitaMedica(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_CitasMedicas().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult baja(int IdCita)
        {
            bool respuesta = false;
           
            respuesta = new CN_CitasMedicas().baja(IdCita);
            return Json(new { resultado = respuesta}, JsonRequestBehavior.AllowGet);

        }
        public ActionResult baja2(int IdCita)
        {
            bool respuesta = false;

            respuesta = new CN_CitasMedicas().baja2(IdCita);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);

        }
        #endregion


        //***************** PACIENTES ********************
        #region  PACIENTE


        [HttpGet]
        public ActionResult ListarPacientes()
        {

            List<Paciente> olista = new List<Paciente>();

            olista = new CN_Paciente().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarPacientes(Paciente objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.COD_PACIENTE == 0)
            {
                resultado = new CN_Paciente().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Paciente().Editar(objeto, out mensaje);

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EliminarPaciente(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Paciente().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region MENU
        [HttpGet]
        public JsonResult VistaMenu()
        {
            MenuMedico objeto = new CN_MenuMedico().verMenu();
            return Json(new {resultado = objeto}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ListaReportesCitas(string fechainicio, string fechafin)
        {
            List<ReporteCitas> olista = new List<ReporteCitas>();
            olista = new CN_Reportes().ReporteCitas(fechainicio, fechafin);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public JsonResult ListaReportesCitas2(string fechainicio, string fechafin)
        {
            List<ReporteCitas> olista = new List<ReporteCitas>();
            olista = new CN_Reportes().ReporteCitas2(fechainicio, fechafin);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public FileResult ExportarCitas(string fechainicio, string fechafin)
        {
            List<ReporteCitas> oLista = new List<ReporteCitas>();
            oLista = new CN_Reportes().ReporteCitas(fechainicio, fechafin);

            DataTable dt = new DataTable();
            dt.Locale = new System.Globalization.CultureInfo("es-PE");
            dt.Columns.Add("FechaIngreso", typeof(string));
            dt.Columns.Add("Paciente", typeof(string));
            dt.Columns.Add("Medico", typeof(string));
            dt.Columns.Add("PrecioCita", typeof(decimal));
            dt.Columns.Add("Cantidad", typeof(int));

            foreach (ReporteCitas rp in oLista)
            {
                dt.Rows.Add(new object[]
                {
                    rp.FechaIngreso,
                    rp.Paciente,
                    rp.Medico,
                    rp.PrecioCita,
                    rp.Cantidad


                });
            }

            dt.TableName = "Datos";
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Reporte de Citas " + DateTime.Now.ToString() + ".xlsx");
                }
            }

        }




        #endregion

    }
}

CapaAsilo/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;

namespace CapaAsilo.Controllers
{
    public class PersonalController : Controller
    {
        // GET: Personal
        #region VISTAS
        public ActionResult Medico()
        {
            return View();
        }
        public ActionResult Enfermero()
        {
            return View();
        }
        #endregion

        #region MEDICO
        [HttpGet]
        public ActionResult ListarMedico()
        {

            List<Medico> olista = new List<Medico>();

            olista = new CN_Medico().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarMedico(Medico objeto)
         {
            object resultado;
            string mensaje = string.Empty;
            if(objeto.IdMedico == 0)
            {
                resultado = new CN_Medico().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado= new CN_Medico().Editar(objeto, out mensaje);
            }

            return Json(new {resultado = resultado, mensaje= mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarMedico(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty ;
            respuesta = new CN_Medico().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        // enfermero 
        #region ENFERMERO
        [HttpGet]
        public ActionResult ListarEnfermero()
        {

            List<Enfermero> olista = new List<Enfermero>();

            olista = new CN_Enfermero().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult GuardarEnfermero(Enfermero objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdEnfermero == 0)
            {
                resultado = new CN_Enfermero().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Enfermero().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarEnfermero(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Enfermero().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion


    }
}

CapaAsilo/Views/Personal/Enfermero.cshtml
@{
    ViewBag.Title = "Enfermero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Personal</a></li>
    <li class="breadcrumb-item active">Enfermeros</li>
</ol>

<div class="card">
    <img class="card-img-top" src="https://thumbs.dreamstime.com/b/m%C3%A9dico-mujer-con-estetoscopio-en-banner-horizontal-del-hospital-sosteniendo-un-cartel-sobre-el-fondo-200769310.jpg" height="300">
    <div class="card-body">
        <i class="fas fa-user-md me-2"></i>Lista de Enfermeros
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-primary" onclick="abrirModal(null)">Nuevo Enfermero</button>
            </div>
        </div>

        <hr />
        <table id="tabla" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            </tbody>
        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="formModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Enfermero</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                <input id="txtid" type="hidden" value="0" />
                <div class="row g-2">

                    <div class="col-sm-6">
                        <label for="txtnombre">Nombres</label>
                        <input type="text" class="form-control" id="txtnombre" placeholder="Ingrese su Nombre" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="txtapellido">Apellidos</label>
                        <input type="text" class="form-control" id="txtapellido" placeholder="Ingrese su Apellido" autocomplete="off">
                    </div>

                </div>
                @{
                    if (ViewBag.Error != null)
                    {
                        <div class="form-floating mb-3">
                            <div class="alert alert-danger" role="alert">
                                @ViewBag.Error
                            </div>
                        </div>


                    }



                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{ 
    <script>
        var tabladata;
        var filaseleccionada;

        //para listar los datos
           tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarEnfermero", "Personal")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "Nombre" },
                { "data": "Apellido" },
                {
                    "defaultContent": '<button type="button" class="btn btn-outline-primary btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-outline-danger ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"


                }

            ],
            "language": {
                "url": '//cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json'
            }

        });

        //para ingresar datos
        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtnombre").val("");
            $("#txtapellido").val("");


            $("#mensajeError").hide();




            if (json != null) {
                $("#txtid").val(json.IdEnfermero);
                $("#txtnombre").val(json.Nombre);
                $("#txtapellido").val(json.Apellido);


            }



            $("#formModal").modal("show");

        }
        $("#tabla tbody").on("click", ".btn-editar", function () {

            filaseleccionada = $(this).closest("tr");

            var data = tabladata.row(filaseleccionada).data();
            abrirModal(data)
        })


        $("#tabla tbody").on("click", ".btn-eliminar", function () {

            var medicoseleccionado = $(this).closest("tr");

            var data = tabladata.row(medicoseleccionado).data();
            swal ({
                title: "Esta Seguro",
                text: "Desea Eliminar el Medico",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                jQuery.ajax({
                url: '@Url.Action("EliminarEnfermero", "Personal")',
                    type: "POST",
                    data: JSON.stringify({ id: data.IdEnfermero }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.resultado) {
                        tabladata.row(medicoseleccionado).remove().draw();
                    } else {
                        swal("No se pudo Eliminar", data.mensaje, "error")
                    }
                },
                error: function (error) {

                    },
                    beforeSend: function () {

                    }

            });


                });

            console.log(data)
        })


        function guardar() {

            var Enfermero = {
                IdEnfermero: $("#txtid").val(),
                Nombre: $("#txtnombre").val(),
                Apellido: $("#txtapellido").val(),
            
            }
            jQuery.ajax({
                url: '@Url.Action("GuardarEnfermero","Personal")',
                type: "POST",
                data: JSON.stringify({ objeto: Enfermero }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");

                    //Medico Nuevo
                    if (Enfermero.IdEnfermero == 0) {

                        if (data.resultado != 0) {
                            Enfermero.IdEnfermero = data.resultado;
                            tabladata.row.add(Enfermero).draw(false);
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }
                    //Medico editar
                    else {

                        if (data.resultado) {
                            tabladata.row(filaseleccionada).data(Enfermero).draw(false);
                            filaseleccionada = null;
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }


                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();

                },
                beforeSend: function (){
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }

            });



        }


    </script>

}

CapaAsilo/Views/Personal/Medico.cshtml
@{
    ViewBag.Title = "Medico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Personal</a></li>
    <li class="breadcrumb-item active">Medicos</li>
</ol>

<div class="card">
    <img class="card-img-top" src="https://thumbs.dreamstime.com/b/m%C3%A9dico-mujer-con-estetoscopio-en-banner-horizontal-del-hospital-sosteniendo-un-cartel-sobre-el-fondo-200769310.jpg" height="300">
    <div class="card-body">
        <i class="fas fa-user-md me-2"></i>Lista de Medicos
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-primary" onclick="abrirModal(null)">Nuevo Medico</button>
            </div>
        </div>

        <hr />
        <table id="tabla" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Correo</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            </tbody>
        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="formModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Medico</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                <input id="txtid" type="hidden" value="0" />
                <div class="row g-2">

                    <div class="col-sm-6">
                        <label for="txtnombre">Nombres</label>
                        <input type="text" class="form-control" id="txtnombre" placeholder="Ingrese su Nombre" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="txtapellido">Apellidos</label>
                        <input type="text" class="form-control" id="txtapellido" placeholder="Ingrese su Apellido" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="correo">Correo</label>
                        <input type="email" class="form-control" id="correo" placeholder="Ingrese su Correo" autocomplete="off">
                    </div>
                    <div class="col-sm-6">

                        <label for="activo" class="form-label">Activo</label>
                        <select class="form-select" id="activo">
                            <option value="1">Si</option>
                            <option value="0">No</option>

                        </select>
                    </div>

                </div>


                @{
                    if (ViewBag.Error != null)
                    {
                        <div class="form-floating mb-3">
                            <div class="alert alert-danger" role="alert">
                                @ViewBag.Error
                            </div>
                        </div>


                    }



                }


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="guardar()" >Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{

    <script>
        var tabladata;
        var filaseleccionada;

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarMedico", "Personal")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "Nombre" },
                { "data": "Apellido" },
                { "data": "Correo" },
                {
                    "data": "Activo", "render": function (valor) {
                        if (valor) {
                            return "Si"
                        } else {
                            return "No"
                        }
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-outline-primary btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-outline-danger ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"


                }

            ],
            "language": {
                "url": '//cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json'
            }

        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtnombre").val("");
            $("#txtapellido").val("");
            $("#correo").val("");
            $("#activo").val(1);

            $("#mensajeError").hide();




            if (json != null) {
                $("#txtid").val(json.IdMedico);
                $("#txtnombre").val(json.Nombre);
                $("#txtapellido").val(json.Apellido);
                $("#correo").val(json.Correo);
                $("#activo").val(json.Activo == true ? 1:0 );

            }



            $("#formModal").modal("show");

        }


        $("#tabla tbody").on("click", ".btn-editar", function () {

            filaseleccionada =  $(this).closest("tr");

           var data= tabladata.row(filaseleccionada).data();
            abrirModal(data)
        })


        $("#tabla tbody").on("click", ".btn-eliminar", function () {

            var medicoseleccionado = $(this).closest("tr");

            var data = tabladata.row(medicoseleccionado).data();
            swal ({
                title: "Esta Seguro",
                text: "Desea Eliminar el Medico",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                jQuery.ajax({
                url: '@Url.Action("EliminarMedico", "Personal")',
                    type: "POST",
                    data: JSON.stringify({ id: data.IdMedico }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.resultado) {
                        tabladata.row(medicoseleccionado).remove().draw();
                    } else {
                        swal("No se pudo Eliminar", data.mensaje, "error")
                    }
                },
                error: function (error) {

                    },
                    beforeSend: function () {

                    }

            });


                });

            console.log(data)
        })



        function guardar() {

            var Medico = {
                IdMedico: $("#txtid").val(),
                Nombre: $("#txtnombre").val(),
                Apellido: $("#txtapellido").val(),
                Correo: $("#correo").val(),
                Activo: $("#activo").val() == 1 ? true:false,
            }
            jQuery.ajax({
                url: '@Url.Action("GuardarMedico","Personal")',
                type: "POST",
                data: JSON.stringify({ objeto: Medico }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");

                    //Medico Nuevo
                    if (Medico.IdMedico == 0) {

                        if (data.resultado != 0) {
                            Medico.IdMedico = data.resultado;
                            tabladata.row.add(Medico).draw(false);
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }
                    //Medico editar
                    else {

                        if (data.resultado) {
                            tabladata.row(filaseleccionada).data(Medico).draw(false);
                            filaseleccionada = null;
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }


                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();

                },
                beforeSend: function (){
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }

            });


           
        }



    </script>


}