CapaAsilo/Controllers/EspecialistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;


namespace CapaAsilo.Controllers
{
   
    public class EspecialistaController : Controller
    {
        // GET: Especialista
        #region Vistas
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AsignarMedicina()
        {
            return View();
        }

        public ActionResult HistorialEspacialista()
        {
            return View();
        }

        #endregion

        #region Listar Costos del Medico
        //para listar los costos
        [HttpGet]
        public JsonResult ListaCostoMedicos(int IdCita)
        {
            List<CostoMedico> olista = new List<CostoMedico>();
            olista = new CN_CostosMedico().ListaCostoMedicos(IdCita);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Medicamentos
        //para listar los medicamentos
        [HttpGet]
        public JsonResult ListaMedicamentos(int IdCita)
        {
            List<CostoMedico> olista = new List<CostoMedico>();
            olista = new CN_CostosMedico().ListaMedicamentos(IdCita);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Costos

        //eliminar un costo
        [HttpPost]
        public JsonResult EliminarCosto(int id, int i)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_CostosMedico().Eliminar(id, i, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Informacion del Paciente
        //para visualizar la info del paciente

        public JsonResult List_Paciente(int IdCita)
        {
            VerPaciente objeto = new CN_CostosMedico().List_Paciente(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Asignacion de Examenes
        //para guardar la asignacion de examenes
        [HttpPost]
        public JsonResult RegistrarCosto(CostoMedico objeto)
        {

            object resultado;
            string mensaje = string.Empty;


            resultado = new CN_CostosMedico().Registrar(objeto, out mensaje);



            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }
        #endregion
        //metodo para listar la agenda del dia

        #region Agenda
        [HttpGet]
        public JsonResult listarAgenda(int IdEspecialista)
        {
            List<ListarAgenda> olista = new List<ListarAgenda>();
            olista = new CN_ListarAgenda().listarAgenda(IdEspecialista);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

    }
}

CapaAsilo/Controllers/LaboratorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;

namespace CapaAsilo.Controllers
{
    
    public class LaboratorioController : Controller
    {
        // GET: Laboratorio
        #region VISTA
        public ActionResult Laboratorio()
        {
            return View();
        }

        public ActionResult AsignarExamenes()
        {
            return View();
        }
        #endregion

        //metodo para listar los examenes

        #region EXAMENES

        [HttpGet]
        public ActionResult ListarExamen()
        {

            List<DetalleCita> olista = new List<DetalleCita>();

            olista = new CN_Examen().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarExamen(DetalleCita objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdDetalleCita == 0)
            {
                resultado = new CN_Examen().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Examen().Editar(objeto, out mensaje);

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EliminarExamen(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Examen().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //metodo para asignar resultados 
        #region RESULTADOS
        [HttpPost]
        public JsonResult DarResultado(AsignarResultados objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            resultado = new CN_CitasMedicas().DarResultado(objeto, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion
    }
}

CapaAsilo/Views/Laboratorio/AsignarExamenes.cshtml
@{
    ViewBag.Title = "AsignarExamenes";
    Layout = "~/Views/Shared/_Laboratorio.cshtml";
}

<h2>Asignar Resultados de Examen</h2>

<form>
    <div class="row" style="border:inset;margin-bottom:10px; display:block">

        <div class="col-sm-3 m-2">
            <div class="mb-2" style="display:flex">

                <label for="cita">No. Ficha:  </label>
                <input type="text" class="form-control m-2" id="txtIdCita">
                <button type="button" class="btn btn-primary m-2" id="btnbuscar" onclick="cambiar()">Buscar</button>
            </div>

        </div>
        <label class="text-center">FICHA MEDICA</label>
        <hr />
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="fecha"><b>Fecha de Visita: </b></label>
                <label id="fecha"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="paciente"><b>Paciente: </b></label>
                <label id="paciente"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="medico"><b>Medico: </b></label>
                <label id="medico"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="padecimiento"><b>Padecimientos:</b></label>
                <label id="padesimiento"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="motivo"><b>Motivo de Visita: </b></label>
                <label id="motivo"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="estado"><b>Estado:</b></label>
                <label id="estado"> </label>

            </div>

        </div>
        <div class="row mt-2">
            <div class="col-12">

                <div id="mensajeError2" class="alert alert-danger" role="alert">
                    A simple danger alert—check it out!
                </div>

            </div>

        </div>

    </div>


</form>
<form id="contenedor2" class="row" style="background-color:burlywood; border:black">

    <div class="col-sm-9">
        <div class="mb-5">
            <br />
            <div class="row">
                <div class="col-12">
                    <button type="button" class="btn btn-success" onclick="abrilModal(null)">
                        <span class="fas fa-plus-circle"> </span>
                        ASIGNAR RESULTADOS DE EXAMEN

                    </button>
                </div>
            </div>




        
            <br />
            <div class="row mt-1">
                <div class="col-12">

                    <div id="EnvioResul" class="alert alert-danger" role="alert">
                        A simple danger alert—check it out!
                    </div>

                </div>

            </div>
        </div>



    </div>

    <div class="card-body" style="border:dashed">
        <hr />
        <table id="usuario" class="display cell-borde" style="width:100%">
            <thead style="background-color:aquamarine; color:black">
                <tr>
                    <th>No Cita</th>
                    <th>Examen</th>
                    <th>Descripcion</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</form>



<!-- Modal -->
<div class="modal fade" id="FormUsuario" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background: #00E3E0" ; color: black">
                 <h5 class="modal-title" id="exampleModalLabel"><span class="fas fa-comment-medical"></span>    Ingresar los Resultados</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" >
                @*<div class="row g-1" style="background-color:gainsboro">*@

              

           

                <label class="form-label"><b>Ingresar Resultados de examen:</b></label>


                <textarea type="text" class="form-control" id="txtResultados" name="Resultados"></textarea>



                @*</div>*@
                <div class="row mt-2">
                    <div class="col-12" style="background-color:chartreuse">

                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>

                    </div>

                </div>
            </div>
            <div class="modal-footer" style="background-color: #022C2C ">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal" style="position: relative; right: 175px">
                    <span>X </span>
                    Cerrar
                </button>
                <button type="button" class="btn btn-success m-2" id="btDarResultados" onclick="DarResultados();timpoAlert ()">
                    <span class="fas fa-save"></span>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>







@section scripts {

    <script>



        var tabladata;
        var filaSeleccionada;

        $(document).ready(function () {
            $("#mensajeError2").hide();
            $("#EnvioResul").hide();
        })
        function timpoAlert() {
            setTimeout(function () {
                $("#EnvioResul").fadeOut(1500);
            }, 6000);
        }


         $(function () {
            $("#btnbuscar").on("click", function () {


                $("#mensajeError2").hide();
                debugger;
                jQuery.ajax({
                    url: '@Url.Action("List_Paciente", "Especialista")' +
                        "?IdCita=" + $("#txtIdCita").val(),
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        debugger;

                        var ob = data.resultado;



                        $("#txtIdCita").val(ob.IdCita)
                        $("#fecha").text(ob.Fecha)
                        $("#paciente").text(ob.Nombre)
                        $("#medico").text(ob.Medico)
                        $("#padesimiento").text(ob.Padecimientos)
                        $("#motivo").text(ob.MotivoVisita)
                        $("#estado").text(ob.Descripcion)





                    }

                });

            });

        })

          $("#btnbuscar").on("click", function () {
            debugger;
            var Url = '@Url.Action("ListaMedicamentos", "Especialista")' +
            "?IdCita=" + $("#txtIdCita").val();

        tabladata = $("#usuario").DataTable({

                        responsive: true,
                        ordering: false,
                        "ajax": {
                            url: Url,
                            type: "GET",
                            dataType: "json"
                        },
                        "columns":
                        [
                                {

                                "data": "oCitaMedica", "render": function (data) {

                                        return data.IdCita
                                    }
                                },

                                { "data": "oIdDetalleCita", "render": function (data) { return data.Nombre } },
                                { "data": "oIdDetalleCita", "render": function (data) { return data.Descripcion } },
                            {
                                "defaultContent":
                                    ' <button type="button" class="btn btn-outline-dark btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                                "orderable": false,
                                "searchable": false,
                                "width": "90px"
                            }
                        ],
                        "language": {
                            "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            },
            retrieve: true,
            paging: false
                    });
        });

         //
    $("#btnbuscar").on("click", function () {
                  var nueva_url = '@Url.Action("ListaMedicamentos", "Especialista")' +
                      "?IdCita=" + $("#txtIdCita").val()

            tabladata.ajax.url(nueva_url).load();


    })

        function cambiar() {

            var ci = document.getElementById('txtIdCita').value;
            document.getElementById('txtIdCita').value = ci;

            var c = document.getElementById('txtResultados').value;
            document.getElementById('txtResulta dos').value = c;
        }



        function DarResultados() {
            var DarResultados = {

                IdCita: $("#txtIdCita").val(),
                Resultados: $("#txtResultados").val()

            }
              jQuery.ajax({
                url: '@Url.Action("DarResultado", "Laboratorio")',
                type: "POST",
                data: JSON.stringify({ objeto: DarResultados }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");




                        if (data.resultado != false) {

                            DarResultados.IdCita = data.resultado;
                            //tabladata.row.add(Especialidad).draw(false);
                            //$("#FormUsuario").modal("hide");

                            $("#EnvioResul").text("Sean dado los resultados con exitos");
                            $("#EnvioResul").show();
                            $("#txtResultados").val("")



                        } else {
                            $("#EnvioResul").text(data.mensaje);
                            $("#EnvioResul").show();
                        }



                  },
                  error: function (error) {
                      $(".modal-body").LoadingOverlay("hide");
                      $("#mensajeError").text("Error Ajax");
                      $("#mensajeError").show();
                  },
                  beforeSend: function () {
                      $(".modal-body").LoadingOverlay("show", {
                          imageResizeFactor: 2,
                          text: "Cargando...",
                          size: 14
                      })
                  }

            });


      }


        function abrilModal(json) {
          

           



            $("#mensajeError").hide();

            if (json != null) {

                $("#txtIdCita").val(json.IdCita);



            }





            $("#FormUsuario").modal("show");

        }





    </script>

}

CapaAsilo/Views/Laboratorio/Laboratorio.cshtml
@{
    ViewBag.Title = "Laboratorio";
    Layout = "~/Views/Shared/_Laboratorio.cshtml";
}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Laboratorio</a></li>
    <li class="breadcrumb-item active">Examenes</li>
</ol>

<div class="card">
    <img class="card-img-top" src="https://img.freepik.com/vector-premium/medico-dibujos-animados-mascara-protectora-lista-verificacion-portapapeles-diseno_52569-1688.jpg?w=2000" height="290" style="border:dashed">
    <div class="card-body" style="background-color:antiquewhite">
        <i class="fas fa-user-md me-2"></i><b>Lista de Examenes</b>
    </div>
    <div class="card-body" style="background-color: burlywood; padding: 3px 10px; border: PowderBlue 5px solid; border-radius:10px">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-primary" onclick="abrirModal(null)">Ingresar Examen</button>
            </div>
        </div>

        <hr />
        <table id="pacientes" class="display cell-border" style="width: 100%; border: white groove; ">
            <thead>
                <tr>
                    <th>No Examen</th>
                    <th>Examen</th>
                    <th>Descripcion</th>
                    <th>Precio de Examen</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            </tbody>
        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="formModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Datos del Examenes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                <input id="txtid" type="hidden" value="0" />
                <input id="txtidtipo" type="hidden" value="1" />
                <div class="row g-2">

                    <div class="col-sm-6">
                        <label for="txtnombre">Examen</label>
                        <input type="text" class="form-control" id="txtnombre" placeholder="Ingrese Nombre del examen" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="txtapellido">Descripcion</label>
                        <input type="text" class="form-control" id="txtapellido" placeholder="Ingrese la Descripcion" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="padecimientos">Precio</label>
                        <input type="text" class="form-control" id="padecimientos" autocomplete="off">
                    </div>

                </div>
                <div class="row g-2">
                    <div class="col-sm-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            This is a danger alert—check it out!
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{

    <script>



        var tabladata;
        var filaseleccionada;

        tabladata = $("#pacientes").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarExamen", "Laboratorio")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "IdDetalleCita" },
                { "data": "Nombre" },
                { "data": "Descripcion" },
                { "data": "Precio" },

                {
                    "defaultContent": '<button type="button" class="btn btn-outline-primary btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-outline-danger ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"


                }

            ],
            "language": {
                "url": '//cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json'
            }

        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtnombre").val("");
            $("#txtapellido").val("");
            $("#padecimientos").val("");
            $("#txtidtipo").val(1);

            $("#mensajeError").hide();




            if (json != null) {
                $("#txtid").val(json.IdDetalleCita);
                $("#txtnombre").val(json.Nombre);
                $("#txtapellido").val(json.Descripcion);
                $("#padecimientos").val(json.Precio);
                $("#txtidtipo").val(1);


            }



            $("#formModal").modal("show");

        }
        //para editar los pacientes
        $("#pacientes tbody").on("click", ".btn-editar", function () {

            filaseleccionada = $(this).closest("tr");

            var data = tabladata.row(filaseleccionada).data();
            abrirModal(data)
        })

        //para eleiminar los pacientes

        $("#pacientes tbody").on("click", ".btn-eliminar", function () {

            var pacienteseleccionado = $(this).closest("tr");

            var data = tabladata.row(pacienteseleccionado).data();
            swal ({
                title: "Esta Seguro",
                text: "Desea Eliminar el Paciente",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                jQuery.ajax({
                url: '@Url.Action("EliminarExamen", "Laboratorio")',
                    type: "POST",
                    data: JSON.stringify({ id: data.IdDetalleCita }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.resultado) {
                        tabladata.row(pacienteseleccionado).remove().draw();
                    } else {
                        swal("No se pudo Eliminar", data.mensaje, "error")
                    }
                },
                error: function (error) {

                    },
                    beforeSend: function () {

                    }

            });


                });

            console.log(data)
        })
         //PARA GUARDAR EL EXAMEN EN LA BASE DE DATOS
        function guardar() {

            var Paciente = {
                IdDetalleCita: $("#txtid").val(),
                Nombre: $("#txtnombre").val(),
                Descripcion: $("#txtapellido").val(),
                Precio: $("#padecimientos").val(),
                oTipoDetalleCita: {
                   Idtipo: $("#txtidtipo").val(),
                } 
               
            }
            jQuery.ajax({
                url: '@Url.Action("GuardarExamen", "Laboratorio")',
                type: "POST",
                data: JSON.stringify({ objeto: Paciente }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");

                    //Paciente Nuevo
                    if (Paciente.IdDetalleCita == 0) {

                        if (data.resultado != 0) {
                            Paciente.IdDetalleCita = data.resultado;
                            tabladata.row.add(Paciente).draw(false);
                            $("#formModal").modal("hide");
                        }
                        else {

                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }
                    //paciente editar
                    else {

                        if (data.resultado) {
                            tabladata.row(filaseleccionada).data(Paciente).draw(false);
                            filaseleccionada = null;
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }


                },
                error: function (error) {
                   $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();

                },
                beforeSend: function (){
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }

            });



        }


    </script>

}