CapaAsilo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;

namespace CapaAsilo.Controllers
{
  
    public class HomeController : Controller
    {
        #region VISTAS
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Donaciones()
        {
            return View();
        }

        public ActionResult Pagos()
        {
            return View();
        }
        #endregion

        //Donaciones
        #region DONACIONES
        [HttpGet]
        public ActionResult ListarDonaciones()
        {

            List<Donacion> olista = new List<Donacion>();

            olista = new CN_Donacion().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        // guardar donacion
        [HttpPost]
        public ActionResult GuardarDonaciones(Donacion objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdDonacion == 0)
            {
                resultado = new CN_Donacion().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Donacion().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarDonaciones(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Donacion().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //Pagos de Mensualidad
        #region MENSUALIDAD
        [HttpGet]
        public ActionResult ListarPagos()
        {

            List<Mensualidad> olista = new List<Mensualidad>();

            olista = new CN_PagoMensualidad().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        // guardar pago de mensualidad
        [HttpPost]
        public ActionResult GuardarPagos(Mensualidad objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdMensualidad == 0)
            {
                resultado = new CN_PagoMensualidad().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_PagoMensualidad().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarPagos(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_PagoMensualidad().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

    }
}

CapaAsilo/Controllers/MantenimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;

namespace CapaAsilo.Controllers
{
    public class MantenimientoController : Controller
    {
    
        // GET: Mantenimiento
        #region VISTAS
        public ActionResult Usuarios()
        {
            return View();
        }
        public ActionResult Especialista()
        {
            return View();
        }
        public ActionResult Especialidad()
        {
            return View();
        }
        public ActionResult Turno()
        {
            return View();
        }
        public ActionResult EstadoCita()
        {
            return View();
        }
        public ActionResult Fundacion() { 
            return View();
        }
        public ActionResult Mes()
        {
            return View();
        }
        public ActionResult Gastos()
        {
            return View();
        }
        public ActionResult GastosFundacion()
        {
            return View();
        }
        #endregion

        //***************** USUARIO ********************
        #region USUARIOS
        [HttpGet]
        public ActionResult ListarUsuarios()
        {

            List<Usuario> olista = new List<Usuario>();

            olista = new CN_Usuario().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        // guardar usuario
        [HttpPost]
        public ActionResult GuardarUsuario(Usuario objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.ID_USUARIO == 0)
            {
                resultado = new CN_Usuario().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Usuario().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Usuario().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion


        //***************** ESPECIALIDAD ********************
        #region ESPECIALIDAD
        [HttpGet]
        public ActionResult ListarEspecialidad()
        {

            List<Especialidad> olista = new List<Especialidad>();

            olista = new CN_Especialidad().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GuardarEspecialidad(Especialidad objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdEspecialidad == 0)
            {
                resultado = new CN_Especialidad().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Especialidad().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarEspecialidad(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Especialidad().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //***************** ESPECIALISTA ********************
        #region ESPECIALISTA
        [HttpGet]
        public ActionResult ListarEspecialista()
        {

            List<Especialista> olista = new List<Especialista>();

            olista = new CN_Especialista().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GuardarEspecialista (Especialista objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdEspecialista == 0)
            {
                resultado = new CN_Especialista().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Especialista().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarEspecialista(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Especialista().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //***************** TURNOS ********************
        #region TURNO
        [HttpGet]
        public ActionResult ListarTurno()
        {

            List<Turno> olista = new List<Turno>();

            olista = new CN_Turno().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GuardarTurno(Turno objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.NoTurno == 0)
            {
                resultado = new CN_Turno().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Turno().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarTurno(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Turno().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //***************** ESTADOS ********************
        #region ESTADO DE CITA
        [HttpGet]
        public ActionResult ListarEstados()
        {

            List<Estado> olista = new List<Estado>();

            olista = new CN_Estados().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarEstado(Estado objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdEstado == 0)
            {
                resultado = new CN_Estados().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Estados().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarEstado(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Estados().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion


        //***************** FUNDACION ********************
        #region FUNDACION
        [HttpGet]
        public ActionResult ListarFundacion()
        {

            List<Fundacion> olista = new List<Fundacion>();

            olista = new CN_Fundacion().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarFundacion(Fundacion objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdFundacion == 0)
            {
                resultado = new CN_Fundacion().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Fundacion().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarFundacion(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Fundacion().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion

        //***************** MESES ********************
        #region MESES
        [HttpGet]
        public ActionResult ListarMeses()
        {

            List<Mes> olista = new List<Mes>();

            olista = new CN_Mes().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarMes(Mes objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdMes == 0)
            {
                resultado = new CN_Mes().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Mes().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarMes(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Mes().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

CapaAsilo/Views/Home/Donaciones.cshtml
@{
    ViewBag.Title = "Donaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Modulo Ingresos</a></li>
    <li class="breadcrumb-item active">Donaciones</li>
</ol>

<div class="card">
    <img class="card-img-top" src="~/Img/contabilidad.png" height="300">
    <div class="card-body">
        <i class="fas fa-user-md me-2"></i>Lista de Donaciones
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-primary" onclick="abrirModal(null)">Quiero Donar</button>
            </div>
        </div>

        <hr />
        <table id="tabla1" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>No. Donacion</th>
                    <th>Nombre del Donante</th>
                    <th>Monto a Donar</th>
                    <th>Beneficiario</th>
                    <th>Fecha de Donacion</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            </tbody>
        </table>

    </div>
</div>


<div class="modal fade" id="formModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Datos de la Donacion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                <input id="txtid" type="hidden" value="0" />
                <div class="row g-2">

                    <div class="col-sm-6">
                        <label for="txtdonante">Nombre del Donante:</label>
                        <input type="text" class="form-control" id="txtdonante" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="monto">Monto a Donar?</label>
                        <input type="number" class="form-control" id="monto" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label class="form-label">Fundacion:</label>
                        <select id="cbofundacion" class="form-control">
                        </select>
                    </div>


                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            This is a danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>

        var tabladata;
        var filaseleccionada;

        tabladata = $("#tabla1").DataTable({

            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarDonaciones", "Home")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "IdDonacion" },
                { "data": "Donante" },
                { "data": "MontoDonado" },
                {
                    "data": "oFundacion", "render": function (data) {
                        return data.NombreFundacion
                    }
                },
                { "data": "Fecha" },

                {
                    "defaultContent": '<button type="button" class="btn btn-outline-primary btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-outline-danger ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"


                }

            ],
            "language": {
                "url": '//cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json'
            }

        });

        //listar las fundaciones
        jQuery.ajax({
            url: '@Url.Action("ListarFundacion", "Mantenimiento")',
            type: "GET",
            data: null,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
              success: function (data) {

                  console.log(data)

                  $("<option>").attr({ "value": "0", "disabled": "true" }).text("Seleccionar").appendTo("#cbofundacion");
                $.each(data.data, function (index, item) {

                    $("<option>").attr({ "value": item.IdFundacion }).text(item.IdFundacion + ' ->  ' + item.NombreFundacion).appendTo("#cbofundacion");
                })
            },
            error: function (error) {
                console.log(error)
            }
          });


        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtdonante").val("");
            $("#monto").val(0);
            $("#cbofundacion").val($("#cbofundacion option:first").val());


            $("#mensajeError").hide();




            if (json != null) {

                $("#txtid").val(json.IdDonacion);
                $("#txtdonante").val(json.Donante);
                $("#monto").val(json.MontoDonado);
                $("#cbofundacion").val(json.oFundacion.IdFundacion);


            }



            $("#formModal").modal("show");

        }


        $("#tabla1 tbody").on("click", ".btn-editar", function () {

            filaseleccionada = $(this).closest("tr");

            var data = tabladata.row(filaseleccionada).data();
            abrirModal(data)
        })

        $("#tabla1 tbody").on("click", ".btn-eliminar", function () {

            var medicoseleccionado = $(this).closest("tr");

            var data = tabladata.row(medicoseleccionado).data();
            swal ({
                title: "Esta Seguro",
                text: "Desea Eliminar la Donacion",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                jQuery.ajax({
                url: '@Url.Action("EliminarDonaciones", "Home")',
                    type: "POST",
                    data: JSON.stringify({ id: data.IdDonacion }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.resultado) {
                        tabladata.row(medicoseleccionado).remove().draw();
                    } else {
                        swal("No se pudo Eliminar", data.mensaje, "error")
                    }
                },
                error: function (error) {

                    },
                    beforeSend: function () {

                    }

            });


                });

            console.log(data)
        })

        function guardar() {

            var Enfermero = {
                IdDonacion: $("#txtid").val(),
                Donante: $("#txtdonante").val(),
                MontoDonado: $("#monto").val(),
                oFundacion: {
                    IdFundacion: $("#cbofundacion option:selected").val(),
                    NombreFundacion: $("#cbofundacion option:selected").text()
                },
              


            }
            jQuery.ajax({
                url: '@Url.Action("GuardarDonaciones","Home")',
                type: "POST",
                data: JSON.stringify({ objeto: Enfermero }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");

                    //Medico Nuevo
                    if (Enfermero.IdDonacion == 0) {

                        if (data.resultado != 0) {
                            Enfermero.IdDonacion = data.resultado;
                           // tabladata.row.add(Enfermero).draw(false);
                            location.reload();
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }
                    //Medico editar
                    else {

                        if (data.resultado) {
                          //  tabladata.row(filaseleccionada).data(Enfermero).draw(false);
                            location.reload();
                            filaseleccionada = null;
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    }


                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();

                },
                beforeSend: function (){
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }

            });



        }



    </script>
    }

CapaAsilo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1 class="mt-4 text-center">MENU</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>
<div class="row" style="border:ridge">
    <hr />
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body"></div>
            <div class="row">


                <div class="col-sm-9 ">
                    <h6 class="m-1">Cantidad de Usuarios</h6>
                    <h6 id="totalusuario" class="m-1">0</h6>
                </div>
                <div class="col-sm-3">
                    <i class="fas fa-user fa-2x"></i>
                </div>



            </div>


        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body"></div>
            <div class="row">


                <div class="col-sm-9 ">
                    <h6 class="m-1">Cantidad de Medicos</h6>
                    <h6 class="m-1" id="totalmedico">0</h6>
                </div>
                <div class="col-sm-3">
                    <i class="fas fa-user-md fa-2x"></i>
                </div>



            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-dark text-white mb-4">
            <div class="card-body"></div>
            <div class="row">


                <div class="col-sm-9 ">
                    <h6 class="m-1">Cant. de Enfermeros</h6>
                    <h6 class="m-1" id="totalenfermero">0</h6>
                </div>
                <div class="col-sm-3">
                    <i class="fas fa-user-nurse fa-2x"></i>
                </div>



            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body"></div>
            <div class="row">


                <div class="col-sm-9 ">
                    <h6 class="m-1">Cant. de Especialistas</h6>
                    <h6 class="m-1" id="totalespecialista">0</h6>
                </div>
                <div class="col-sm-3">
                    <i class="fas fa-user-md fa-2x"></i>
                </div>



            </div>
        </div>
    </div>


</div>
<br />

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-tags me-1"></i>
        Historial de Fichas
    </div>
    <div class="card-body">

        <form action="@Url.Action("ExportarCitas","Medico" )" method="post">
            <div class="row align-items-end">
                <div class="col-sm-2">
                    <div class="mb-2">
                        <label class="form-label">Fecha de Inicio:</label>
                        <input class="form-control" type="date" id="txtfechainicio" name="fechainicio" style="width:140px" />
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="mb-2">
                        <label class="form-label">Fecha de Final:</label>
                        <input class="form-control" type="date" id="txtfechafin" name="fechafin" style="width:140px" />
                    </div>
                </div>

                <div class="col-sm-2">
                    <div class="d-grid mb-2 m-2">
                        <button class="btn btn-primary" id="btnbuscar" type="button"><i class="fas fa-search"></i>Buscar</button>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="d-grid mb-2">
                        <button class="btn btn-success" type="submit"><i class="fas fa-file-excel"></i>Exportar</button>
                    </div>
                </div>

            </div>
        </form>

        <hr />

        <div class="row">
            <div class="col-sm-12">
                <table id="tabla" class="display cell-border" style="width:100%">
                    <thead>
                        <tr>
                            <th>Fecha Ingreso</th>
                            <th>Paciente</th>
                            <th>Medico</th>
                            <th>Precio Cita</th>
                            <th>Cantidad</th>
                            <th>Estado de Ficha</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>

        </div>


    </div>
</div>


@section scripts{

    <script>



            var tabladata;

                $(document).ready(function () {

                $("#txtfechainicio").datepicker({ dateFormat: 'dd/mm/yy' }).datepicker('setDate', new Date())
                $("#txtfechafin").datepicker({ dateFormat: 'dd/mm/yy' }).datepicker('setDate', new Date())


         });
           // string fechaincio, string fechafin, string idtransaccion

            var Url = '@Url.Action("ListaReportesCitas2", "Medico")' +
                "?fechainicio=" + $("#txtfechainicio").val()+
                "&fechafin=" + $("#txtfechafin").val()


                tabladata = $("#tabla").DataTable({
                    responsive: true,
                    ordering: false,
                    "ajax": {
                        url: Url,
                        type: "GET",
                        dataType: "json"
                    },
                    "columns": [
                        { "data": "FechaIngreso" },
                        { "data": "Paciente" },
                        { "data": "Medico" },
                        { "data": "PrecioCita" },
                        { "data": "Cantidad" },
                        { "data": "Estado" },

                    ],
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
                    }

                });






            $("#btnbuscar").on("click", function () {
                 var nueva_url = '@Url.Action("ListaReportesCitas2", "Medico")' +
                "?fechainicio=" + $("#txtfechainicio").val()+
                "&fechafin=" + $("#txtfechafin").val()

                tabladata.ajax.url(nueva_url).load();
            })








        jQuery.ajax({
            url: '@Url.Action("VistaMenu", "Mantenimiento")',
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
              success: function (data) {

                  var objeto = data.resultado;
                  $("#totalusuario").text(objeto.CantidadUsuario)
                  $("#totalmedico").text(objeto.CantidadMedico)
                  $("#totalenfermero").text(objeto.CantidadEnfermero)
                  $("#totalespecialista").text(objeto.CantidadEspecialista)
            }

          });


    </script>



}