CapaAsilo/Controllers/EspecialistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;


namespace CapaAsilo.Controllers
{
   
    public class EspecialistaController : Controller
    {
        // GET: Especialista
        #region Vistas
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AsignarMedicina()
        {
            return View();
        }

        public ActionResult HistorialEspacialista()
        {
            return View();
        }

        #endregion

        #region Listar Costos del Medico
        //para listar los costos
        [HttpGet]
        public JsonResult ListaCostoMedicos(int IdCita)
        {
            List<CostoMedico> olista = new List<CostoMedico>();
            olista = new CN_CostosMedico().ListaCostoMedicos(IdCita);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Medicamentos
        //para listar los medicamentos
        [HttpGet]
        public JsonResult ListaMedicamentos(int IdCita)
        {
            List<CostoMedico> olista = new List<CostoMedico>();
            olista = new CN_CostosMedico().ListaMedicamentos(IdCita);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Costos

        //eliminar un costo
        [HttpPost]
        public JsonResult EliminarCosto(int id, int i)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_CostosMedico().Eliminar(id, i, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Informacion del Paciente
        //para visualizar la info del paciente

        public JsonResult List_Paciente(int IdCita)
        {
            VerPaciente objeto = new CN_CostosMedico().List_Paciente(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region Asignacion de Examenes
        //para guardar la asignacion de examenes
        [HttpPost]
        public JsonResult RegistrarCosto(CostoMedico objeto)
        {

            object resultado;
            string mensaje = string.Empty;


            resultado = new CN_CostosMedico().Registrar(objeto, out mensaje);



            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }
        #endregion
        //metodo para listar la agenda del dia

        #region Agenda
        [HttpGet]
        public JsonResult listarAgenda(int IdEspecialista)
        {
            List<ListarAgenda> olista = new List<ListarAgenda>();
            olista = new CN_ListarAgenda().listarAgenda(IdEspecialista);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

    }
}

CapaAsilo/Controllers/FarmaciaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaEntidad1.Paypal;
using CapaNegocio;

namespace CapaAsilo.Controllers
{
    public class FarmaciaController : Controller
    {
        // GET: Farmacia
        #region FARMACIA
        public ActionResult Farmacia()
        {
            return View();
        }
        public ActionResult Medicamentos()
        {
            return View();
        }
        #endregion


        #region MEDICAMENTOS

        [HttpGet]
        public ActionResult ListarMedicamento()
        {

            List<DetalleCita> olista = new List<DetalleCita>();

            olista = new CN_Medicamentos().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarMedicamento(DetalleCita objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdDetalleCita == 0)
            {
                resultado = new CN_Medicamentos().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Medicamentos().Editar(objeto, out mensaje);

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EliminarMedicamento(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Medicamentos().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion


        #region DETALLE DE CITAS

        [HttpGet]
        public JsonResult DetalleCita(int IdCita)
        {
            List<VistaCita> olista = new List<VistaCita>();
            olista = new CN_CostosMedico().DetalleCita(IdCita);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);

        }
        public JsonResult Totalcita(int IdCita)
        {
            TotalCita objeto = new CN_CostosMedico().Totalcita(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }
        public JsonResult VerCitas(int IdCita)
        {
            VerCitas objeto = new CN_CostosMedico().VerCitas(IdCita);
            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);

        }

        #endregion

       
        public JsonResult enviarCorreo(string correo, string total)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = CN_EnviarCorreo.Enviar(correo, total, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


    }
}

CapaAsilo/Controllers/LaboratorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad1;
using CapaNegocio;

namespace CapaAsilo.Controllers
{
    
    public class LaboratorioController : Controller
    {
        // GET: Laboratorio
        #region VISTA
        public ActionResult Laboratorio()
        {
            return View();
        }

        public ActionResult AsignarExamenes()
        {
            return View();
        }
        #endregion

        //metodo para listar los examenes

        #region EXAMENES

        [HttpGet]
        public ActionResult ListarExamen()
        {

            List<DetalleCita> olista = new List<DetalleCita>();

            olista = new CN_Examen().Listar();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarExamen(DetalleCita objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdDetalleCita == 0)
            {
                resultado = new CN_Examen().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Examen().Editar(objeto, out mensaje);

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EliminarExamen(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Examen().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        //metodo para asignar resultados 
        #region RESULTADOS
        [HttpPost]
        public JsonResult DarResultado(AsignarResultados objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            resultado = new CN_CitasMedicas().DarResultado(objeto, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion
    }
}

CapaAsilo/Views/Especialista/AsignarMedicina.cshtml
@{
    ViewBag.Title = "AsignarMedicina";
    Layout = "~/Views/Shared/_Especialista.cshtml";
}

<h2>Visita Medica</h2>


<form>
    <div class="row" style="border:inset;margin-bottom:10px; display:block">

        <div class="col-sm-3 m-2">
            <div class="mb-2" style="display:flex">

                <label for="cita">No. Ficha:  </label>
                <input type="text" class="form-control m-2" id="txtIdCita">
                <button type="button" class="btn btn-primary m-2" id="btnbuscar" onclick="cambiar()">Buscar</button>
            </div>

        </div>

        <label class="text-center">FICHA MEDICA</label>
        <hr />
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="fecha"><b>Fecha de Visita: </b></label>
                <label id="fecha"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="paciente"><b>Paciente: </b></label>
                <label id="paciente"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="medico"><b>Medico: </b></label>
                <label id="medico"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="padecimiento"><b>Padecimientos:</b></label>
                <label id="padesimiento"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="motivo"><b>Motivo de Visita: </b></label>
                <label id="motivo"> </label>

            </div>

        </div>
        <div class="col-sm-7">
            <div class="mb-3">

                <label for="estado"><b>Estado:</b></label>
                <label id="estado"> </label>

            </div>

        </div>
        <div class="row mt-2">
            <div class="col-12">

                <div id="mensajeError2" class="alert alert-danger" role="alert">
                    A simple danger alert—check it out!
                </div>

            </div>

        </div>



    </div>




    <div class="card">
        <img class="card-img-top" src="~/Img/medicamentos.jpg" height="300" style="border:dotted">
        <div class="card-header">
            <i class="fas fa-paste me-1"></i><b>Lista de Medicamentos</b>
        </div>
        <div class="card-body" style="background-color:deepskyblue">
            <div class="row">
                <div class="col-12">
                    <button type="button" class="btn btn-success" onclick="abrilModal(null); cambiar()">
                        <span class="fas fa-plus-circle"> </span>
                        ASIGNAR MEDICAMENTOS

                    </button>
                </div>
            </div>


            <hr />

            <table id="usuario" class="display cell-borde" style="width:100%; border:double">
                <thead style="background-color:dodgerblue; color:black">
                    <tr>

                        <th>No medicamento</th>
                        <th>Medicamento</th>
                        <th>Descripcion</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

</form>

<!-- Modal -->
<div class="modal fade" id="FormUsuario" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background:#00ffff; color:black">
                <h5 class="modal-title" id="exampleModalLabel">Asignar Medicamentos</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="background-color: lemonchiffon">
                @*<div class="row g-1" style="background-color:gainsboro">*@

                <input id="txtid" type="hidden" value="0">
                
                @*; position: relative; left: 100px*@

            <div class="col-sm-6" style="background-color: lemonchiffon; left: 100px">

                <label for="txtnombres" class="form-label">Id Cita</label>
                <input type="text" class="form-control" id="cita" autocomplete="off" style="border-color:black">
                <br />
                <label class="form-label">Medicamento:</label>
                <select id="cboMedicamentoExamen" class="form-control" style="width:400px">
                </select>
                <label for="txtdescripcion" class="form-label">Cantidad</label>
                <input type="text" class="form-control" id="txtCantidad" autocomplete="off">



            </div>



                @*</div>*@
                <div class="row mt-2">
                    <div class="col-12" style="background-color:chartreuse">

                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>

                    </div>

                </div>
            </div>
            <div class="modal-footer" style="background-color:lavender">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="position: relative; right: 175px">
                    <span>X </span>
                    Cerrar
                </button>
                <button type="button" class="btn btn-primary" onclick="Guardar() " style="position: relative; right: 165px" id="boton">
                    <span class="fas fa-download"></span>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>


@section scripts{

    <script>

        var tabladata;
        var filaSeleccionada

        $(document).ready(function () {
            $("#mensajeError2").hide();

        })

        $("#btnbuscar").on("click", function () {
            debugger;
            var Url = '@Url.Action("ListaMedicamentos", "Especialista")' +
            "?IdCita=" + $("#txtIdCita").val();

        tabladata = $("#usuario").DataTable({

                        responsive: true,
                        ordering: false,
                        "ajax": {
                            url: Url,
                            type: "GET",
                            dataType: "json"
                        },
                        "columns":
                        [
                                {

                                "data": "oCitaMedica", "render": function (data) {

                                        return data.IdCita
                                    }
                                },

                                { "data": "oIdDetalleCita", "render": function (data) { return data.Nombre } },
                                { "data": "oIdDetalleCita", "render": function (data) { return data.Descripcion } },
                            {
                                "defaultContent":
                                    ' <button type="button" class="btn btn-outline-dark btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                                "orderable": false,
                                "searchable": false,
                                "width": "90px"
                            }
                        ],
                        "language": {
                            "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            },
            retrieve: true,
            paging: false
                    });
        });

         //
    $("#btnbuscar").on("click", function () {
                  var nueva_url = '@Url.Action("ListaMedicamentos", "Especialista")' +
                      "?IdCita=" + $("#cita").val()

            tabladata.ajax.url(nueva_url).load();





         })




             jQuery.ajax({
            url: '@Url.Action("ListarMedicamento", "Farmacia")',
            type: "GET",
            data: null,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
              success: function (data) {

                  console.log(data)

                  $("<option>").attr({ "value": "0", "disabled": "true" }).text("Seleccionar").appendTo("#cboMedicamentoExamen");
                $.each(data.data, function (index, item) {

                    $("<option>").attr({ "value": item.IdDetalleCita }).text(item.IdDetalleCita + '.) ' + item.Nombre).appendTo("#cboMedicamentoExamen");
                })
            },
            error: function (error) {
                console.log(error)
            }
             });


        var id = document.getElementById('txtIdCita').value;

        function cambiar() {

            var ci = document.getElementById('txtIdCita').value;
            document.getElementById('cita').value = ci;

        }
        function abrilModal(json) {


            $("#txtid").val(0);

            $("#txtCantidad").val(1);
            $("#cboMedicamentoExamen").val($("#cboMedicamentoExamen option:first").val());


            $("#mensajeError").hide();


            $("#FormUsuario").modal("show");

        }


         $("#usuario tbody").on("click", '.btn-eliminar', function () {

            var usuarioSeleccionado = $(this).closest("tr");
            var data = tabladata.row(usuarioSeleccionado).data();

            swal({
                title: "Esta Seguro?",
                text: "¿Desea eliminar la examen?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
            function () {
                debugger;
                   jQuery.ajax({
                       url: '@Url.Action("EliminarCosto", "Especialista")',
                       type: "POST",
                       data: JSON.stringify({ id: data.oCitaMedica.IdCita, i: data.oIdDetalleCita.IdDetalleCita }),
                   dataType: "json",
                   contentType: "application/json; charset=utf-8",
                   success: function (data) {

                      if (data.resultado) {
                          tabladata.row(usuarioSeleccionado).remove().draw();
                      }
                      else{
                           swal("No se pudo eliminar", data.mensaje, "error")
                       }
                  },
                   error: function (error) {
                   console.log(error)
                    }
               });




                });

            console.log(data)


         })


         $(function () {
            $("#btnbuscar").on("click", function () {


                $("#mensajeError2").hide();
               
                jQuery.ajax({
                    url: '@Url.Action("List_Paciente", "Especialista")' +
                        "?IdCita=" + $("#cita").val(),
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        debugger;

                        var ob = data.resultado;

                        $("#txtIdCita").val(ob.IdCita)
                        $("#fecha").text(ob.Fecha)
                        $("#paciente").text(ob.Nombre)
                        $("#medico").text(ob.Medico)
                        $("#padesimiento").text(ob.Padecimientos)
                        $("#motivo").text(ob.MotivoVisita)
                        $("#estado").text(ob.Descripcion)
                     




                    }

                });

            });

        }
        )




        function Guardar() {
            $("#mensajeError2").hide();
            debugger;
            var CostoMedico = {

                oCitaMedica:
                {
                    IdCita: $("#cita").val()
                },


                oIdDetalleCita: {
                    IdDetalleCita: $("#cboMedicamentoExamen option:selected").val(),
                    Nombre: $("#cboMedicamentoExamen option:selected").text()
                },
                Cantidad: $("#txtCantidad").val(),
                /* cita cboMedicamentoExamen  txtCantidad*/

            }
            jQuery.ajax({

                url: '@Url.Action("RegistrarCosto", "Especialista")',
                type: "POST",
                data: JSON.stringify({ objeto: CostoMedico }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");





                        if (data.resultado !=0) {

                            CostoMedico.oCitaMedica.IdCita = data.resultado;
                           /* tabladata.row.add(GastosMedicos).draw(false);*/
                            $("#FormUsuario").modal("hide");

                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }



                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }

            });

        }






    </script>

}

CapaAsilo/Views/Especialista/HistorialEspacialista.cshtml
@{
    ViewBag.Title = "HistorialEspacialista";
    Layout = "~/Views/Shared/_Especialista.cshtml";
}


<div class="card">
    <div class="card-header">

        <div class="row" style="background-color:burlywood ; border:solid">
          
                <h1><b>Agenda de Solicitudes.</b></h1>
        
            
            <div class="col-sm-2" style="display:flex">
                <div class="mb-2">
                    <label class="form-label"><b>Tipo de Especialidad:</b></label>
                    <select id="cboEspecialidad" class="form-control" style="width:200px">
                        <option selected>Seleccionar la Opcion</option>
                    </select>
                </div>
                <button type="button" class="btn btn-info m-2" id="btBuscar" >
                    <span class="icon"><i class="fa fa-search"></i></span> Buscar</button>
            </div>
            
        </div>




    </div>
    <div class="card-body" style="border:dashed">

        <hr />

        <table id="usuario" class="display cell-borde" style="width:100%">
            <thead style="background-color:aquamarine; color:black">
                <tr>
                    <th>No Solicitud</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Motivo de Visita</th>
                    <th>Horario</th>

                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>



@section scripts{
    <script>

        var tabladata;
        var filaSeleccionada;








        $("#btBuscar").on("click", function () {
              var Url = '@Url.Action("listarAgenda", "Especialista")' +
            "?IdEspecialista=" + $("#cboEspecialidad").val();

                    tabladata = $("#usuario").DataTable({
                        responsive: true,
                        ordering: false,
                        "ajax": {
                            url: Url,
                            type: "GET",
                            dataType: "json"
                        },
                        "columns":
                        [

                                { "data": "IdEspcialista" },
                                { "data": "Nombre" },
                                { "data": "Apellido" },
                                { "data": "MotivoVisita" },
                                { "data": "horario" }

                        ],
                        "language": {
                            "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
                        },
                        retrieve: true,
                        paging: false
                    });
        });








        $("#btBuscar").on("click", function () {
                  var nueva_url = '@Url.Action("listarAgenda", "Especialista")' +
                      "?IdEspecialista=" + $("#cboEspecialidad").val()

            tabladata.ajax.url(nueva_url).load();
            
            })





                  jQuery.ajax({
            url: '@Url.Action("ListarEspecialidad", "Mantenimiento")',
            type: "GET",
            data: null,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
              success: function (data) {

                  console.log(data)

                 /* $("<option>").attr({ "value": "0", "disabled": "true" }).text("Seleccionar").appendTo("#cboEspecialidad");*/
                $.each(data.data, function (index, item) {

                    $("<option>").attr({ "value": item.IdEspecialidad }).text(item.IdEspecialidad + '.) ' + item.Nombre).appendTo("#cboEspecialidad");
                })
            },
            error: function (error) {
                console.log(error)
            }
          });




    </script>


}